import { RootProvider } from './root-provider'
import './globals.css'

export const metadata = {
  title: 'Test firebase with next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  )
}
